services:

  app:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - .:/app
      - /app/__pycache__
      - /app/.pytest_cache
    env_file:
      - .env
    depends_on:
      - postgres
      - redis
    networks:
      - app-network

  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: ${APP_CONFIG__DB__USERNAME}
      POSTGRES_PASSWORD: ${APP_CONFIG__DB__PASSWORD}
      POSTGRES_DB: ${APP_CONFIG__DB__NAME}
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${APP_CONFIG__DB__USERNAME}"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:8-alpine
    ports:
      - "6379:6379"
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "cache-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:
    external: true
    name: roadmap-learner_postgres_data