"""remove user_id from Block/Card

Revision ID: 74feea4878af
Revises: 8095375c2374
Create Date: 2026-02-18 15:47:11.362004

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "74feea4878af"
down_revision: Union[str, Sequence[str], None] = "8095375c2374"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("fk_blocks_user_id_users"), "blocks", type_="foreignkey")
    op.drop_column("blocks", "user_id")
    op.drop_constraint(op.f("fk_cards_user_id_users"), "cards", type_="foreignkey")
    op.drop_column("cards", "user_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("cards", sa.Column("user_id", sa.UUID(), autoincrement=False, nullable=False))
    op.create_foreign_key(
        op.f("fk_cards_user_id_users"), "cards", "users", ["user_id"], ["id"], ondelete="CASCADE"
    )
    op.add_column("blocks", sa.Column("user_id", sa.UUID(), autoincrement=False, nullable=False))
    op.create_foreign_key(
        op.f("fk_blocks_user_id_users"), "blocks", "users", ["user_id"], ["id"], ondelete="CASCADE"
    )
    # ### end Alembic commands ###
