"""add uniq title Block

Revision ID: 3bd4d6571e1b
Revises: 3fe1c9037e21
Create Date: 2026-03-12 20:11:51.407397

"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "3bd4d6571e1b"
down_revision: str | Sequence[str] | None = "3fe1c9037e21"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index("ix_block_roadmap_order", "blocks", ["roadmap_id", "order_index"], unique=False)
    op.create_unique_constraint(
        "uq_block_roadmap_order",
        "blocks",
        ["roadmap_id", "order_index"],
        deferrable=True,
        initially="DEFERRED",
    )
    op.create_unique_constraint("uq_block_roadmap_title", "blocks", ["roadmap_id", "title"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uq_block_roadmap_title", "blocks", type_="unique")
    op.drop_constraint("uq_block_roadmap_order", "blocks", type_="unique")
    op.drop_index("ix_block_roadmap_order", table_name="blocks")
    # ### end Alembic commands ###
