"""update order_index on Question

Revision ID: 3fe1c9037e21
Revises: 3a0a7a1267bb
Create Date: 2026-03-12 19:55:50.676087

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "3fe1c9037e21"
down_revision: str | Sequence[str] | None = "3a0a7a1267bb"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "blocks",
        "order_index",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        type_=sa.Integer(),
        existing_nullable=False,
    )
    op.drop_constraint(op.f("uq_block_roadmap_order"), "blocks", type_="unique")
    op.drop_constraint(op.f("uq_block_roadmap_title"), "blocks", type_="unique")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        op.f("uq_block_roadmap_title"),
        "blocks",
        ["roadmap_id", "title"],
        postgresql_nulls_not_distinct=False,
    )
    op.create_unique_constraint(
        op.f("uq_block_roadmap_order"),
        "blocks",
        ["roadmap_id", "order_index"],
        postgresql_nulls_not_distinct=False,
    )
    op.alter_column(
        "blocks",
        "order_index",
        existing_type=sa.Integer(),
        type_=sa.DOUBLE_PRECISION(precision=53),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
