"""remove order index from question

Revision ID: a8c0218ca268
Revises: c723d7312cd7
Create Date: 2026-03-27 13:33:18.361005

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a8c0218ca268"
down_revision: str | Sequence[str] | None = "c723d7312cd7"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_question_module_order"), table_name="questions")
    op.drop_constraint(op.f("uq_question_module_order"), "questions", type_="unique")
    op.drop_column("questions", "order_index")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "questions", sa.Column("order_index", sa.INTEGER(), autoincrement=False, nullable=False)
    )
    op.create_unique_constraint(
        op.f("uq_question_module_order"),
        "questions",
        ["module_id", "order_index"],
        postgresql_nulls_not_distinct=False,
    )
    op.create_index(
        op.f("ix_question_module_order"), "questions", ["module_id", "order_index"], unique=False
    )
    # ### end Alembic commands ###
