"""update session to questions

Revision ID: 3a0a7a1267bb
Revises: 26829df7fe8b
Create Date: 2026-03-09 23:38:36.711076

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "3a0a7a1267bb"
down_revision: str | Sequence[str] | None = "26829df7fe8b"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("sessions", sa.Column("questions", sa.ARRAY(sa.UUID()), nullable=True))
    op.add_column("sessions", sa.Column("index", sa.Integer(), nullable=False))
    op.drop_column("sessions", "current_card_index")
    op.drop_column("sessions", "card_ids_queue")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "sessions",
        sa.Column("card_ids_queue", postgresql.ARRAY(sa.UUID()), autoincrement=False, nullable=True),
    )
    op.add_column(
        "sessions",
        sa.Column("current_card_index", sa.INTEGER(), autoincrement=False, nullable=False),
    )
    op.drop_column("sessions", "index")
    op.drop_column("sessions", "questions")
    # ### end Alembic commands ###
