"""question

Revision ID: 9294eb271afb
Revises: fe076e2c9989
Create Date: 2026-03-12 21:12:26.757089

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "9294eb271afb"
down_revision: str | Sequence[str] | None = "fe076e2c9989"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
