"""add nullable to answer in question

Revision ID: 7ee7539bde30
Revises: ad4fb0c75854
Create Date: 2026-03-13 18:41:04.919999

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7ee7539bde30"
down_revision: str | Sequence[str] | None = "ad4fb0c75854"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("questions", "answer", existing_type=sa.TEXT(), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("questions", "answer", existing_type=sa.TEXT(), nullable=False)
    # ### end Alembic commands ###
