"""update order_index in question

Revision ID: dc95a9caf8ba
Revises: 3bd4d6571e1b
Create Date: 2026-03-12 20:47:25.328173

"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "dc95a9caf8ba"
down_revision: str | Sequence[str] | None = "3bd4d6571e1b"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index("ix_question_block_order", "questions", ["block_id", "order_index"], unique=False)
    op.create_unique_constraint("uq_question_block_question", "questions", ["block_id", "question"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uq_question_block_question", "questions", type_="unique")
    op.drop_index("ix_question_block_order", table_name="questions")
    # ### end Alembic commands ###
