"""Add question logic

Revision ID: b19f35d949f2
Revises: 74feea4878af
Create Date: 2026-03-07 13:31:23.563153

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b19f35d949f2"
down_revision: str | Sequence[str] | None = "74feea4878af"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "questions",
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("block_id", sa.Uuid(), nullable=False),
        sa.Column("question", sa.String(length=500), nullable=False),
        sa.Column("answer", sa.Text(), nullable=False),
        sa.Column("order_index", sa.Float(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["block_id"],
            ["blocks.id"],
            name=op.f("fk_questions_block_id_blocks"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_questions")),
        sa.UniqueConstraint("block_id", "order_index", name="uq_question_block_order"),
    )
    op.alter_column(
        "blocks",
        "title",
        existing_type=sa.VARCHAR(length=30),
        type_=sa.String(length=75),
        existing_nullable=False,
    )
    op.alter_column(
        "blocks",
        "description",
        existing_type=sa.VARCHAR(length=100),
        type_=sa.String(length=300),
        existing_nullable=True,
    )
    op.create_unique_constraint("uq_block_roadmap_order", "blocks", ["roadmap_id", "order_index"])
    op.create_unique_constraint("uq_block_roadmap_title", "blocks", ["roadmap_id", "title"])
    op.drop_column("blocks", "status")
    op.add_column("cards", sa.Column("roadmap_id", sa.Uuid(), nullable=False))
    op.alter_column(
        "cards",
        "term",
        existing_type=sa.VARCHAR(length=50),
        type_=sa.String(length=100),
        existing_nullable=False,
    )
    op.alter_column(
        "cards",
        "definition",
        existing_type=sa.VARCHAR(length=100),
        type_=sa.String(length=1000),
        existing_nullable=False,
    )
    op.alter_column(
        "cards",
        "example",
        existing_type=sa.VARCHAR(length=100),
        type_=sa.String(length=1000),
        existing_nullable=True,
    )
    op.alter_column(
        "cards",
        "comment",
        existing_type=sa.VARCHAR(length=100),
        type_=sa.String(length=500),
        existing_nullable=True,
    )
    op.create_unique_constraint("uq_card_roadmap_term", "cards", ["roadmap_id", "term"])
    op.drop_constraint(op.f("fk_cards_block_id_blocks"), "cards", type_="foreignkey")
    op.create_foreign_key(
        op.f("fk_cards_roadmap_id_roadmaps"),
        "cards",
        "roadmaps",
        ["roadmap_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_column("cards", "block_id")
    op.drop_column("cards", "status")
    op.alter_column(
        "roadmaps",
        "title",
        existing_type=sa.VARCHAR(length=30),
        type_=sa.String(length=100),
        existing_nullable=False,
    )
    op.alter_column(
        "roadmaps",
        "description",
        existing_type=sa.VARCHAR(length=100),
        type_=sa.String(length=500),
        existing_nullable=True,
    )
    op.create_unique_constraint("uq_roadmap_user_title", "roadmaps", ["user_id", "title"])
    op.drop_column("roadmaps", "status")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "roadmaps",
        sa.Column(
            "status",
            postgresql.ENUM("draft", "active", "archived", name="roadmap_status"),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.drop_constraint("uq_roadmap_user_title", "roadmaps", type_="unique")
    op.alter_column(
        "roadmaps",
        "description",
        existing_type=sa.String(length=500),
        type_=sa.VARCHAR(length=100),
        existing_nullable=True,
    )
    op.alter_column(
        "roadmaps",
        "title",
        existing_type=sa.String(length=100),
        type_=sa.VARCHAR(length=30),
        existing_nullable=False,
    )
    op.add_column(
        "cards",
        sa.Column(
            "status",
            postgresql.ENUM("unknown", "known", "review", name="card_status"),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.add_column("cards", sa.Column("block_id", sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(op.f("fk_cards_roadmap_id_roadmaps"), "cards", type_="foreignkey")
    op.create_foreign_key(
        op.f("fk_cards_block_id_blocks"),
        "cards",
        "blocks",
        ["block_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_constraint("uq_card_roadmap_term", "cards", type_="unique")
    op.alter_column(
        "cards",
        "comment",
        existing_type=sa.String(length=500),
        type_=sa.VARCHAR(length=100),
        existing_nullable=True,
    )
    op.alter_column(
        "cards",
        "example",
        existing_type=sa.String(length=1000),
        type_=sa.VARCHAR(length=100),
        existing_nullable=True,
    )
    op.alter_column(
        "cards",
        "definition",
        existing_type=sa.String(length=1000),
        type_=sa.VARCHAR(length=100),
        existing_nullable=False,
    )
    op.alter_column(
        "cards",
        "term",
        existing_type=sa.String(length=100),
        type_=sa.VARCHAR(length=50),
        existing_nullable=False,
    )
    op.drop_column("cards", "roadmap_id")
    op.add_column(
        "blocks",
        sa.Column(
            "status",
            postgresql.ENUM("draft", "active", "archived", name="block_status"),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.drop_constraint("uq_block_roadmap_title", "blocks", type_="unique")
    op.drop_constraint("uq_block_roadmap_order", "blocks", type_="unique")
    op.alter_column(
        "blocks",
        "description",
        existing_type=sa.String(length=300),
        type_=sa.VARCHAR(length=100),
        existing_nullable=True,
    )
    op.alter_column(
        "blocks",
        "title",
        existing_type=sa.String(length=75),
        type_=sa.VARCHAR(length=30),
        existing_nullable=False,
    )
    op.drop_table("questions")
    # ### end Alembic commands ###
